### ISSUE TITLE
git submodule update --init --recursive not a git repository

### ISSUE THREAD

**Issue by Conan-Wolf** [makerdao/market-maker-keeper#118]
~/market-maker-keeper-master $ sudo git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git

**Comment by grandizzy** [comment]
It looks like you missed first step here:

https://github.com/makerdao/market-maker-keeper#3-getting-started-installation

git clone git@github.com:makerdao/market-maker-keeper.git
cd market-maker-keeper

Make sure you follow that procedure step by step, e.g. sudo is not required

**Comment by grandizzy** [comment]
updated README to clone https instead ssh https://github.com/makerdao/market-maker-keeper#3-getting-started-installation

**Comment by Conan-Wolf** [comment]
thanks solved my problem :)
