### ISSUE TITLE
now problems with the ./install.sh and ./test.sh

### ISSUE THREAD

**Issue by Conan-Wolf** [makerdao/market-maker-keeper#119]
ERROR: Could not find a version that satisfies the requirement web3==4.8.2 (from versions: 0.1.7, 0.1.8, 0.1.9, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 2.0.0, 2.1.0, 2.1.1, 2.2.0, 2.3.0, 2.4.0, 2.5.0, 2.6.0, 2.7.0, 2.7.1, 2.8.0, 2.8.1, 2.9.0, 3.0.0, 3.0.1, 3.0.2, 3.1.0, 3.1.1, 3.2.0, 3.3.0, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.6.0, 3.6.1, 3.6.2, 3.7.0, 3.7.1, 3.7.2, 3.8.0, 3.8.1, 3.9.0, 3.10.0, 3.11.0, 3.11.1, 3.13.0, 3.13.1, 3.13.2, 3.13.3, 3.13.4, 3.13.5, 3.14.0, 3.14.1, 3.14.2, 3.15.0, 3.16.0, 3.16.1, 3.16.2, 3.16.3, 3.16.4, 3.16.5, 4.0.0b1, 4.0.0b2, 4.0.0b3, 4.0.0b4, 4.0.0b5, 4.0.0b6, 4.0.0b7, 4.0.0b9, 4.0.0b10, 4.0.0b11, 4.0.0b12, 4.0.0b13, 4.0.0, 4.1.0, 4.2.0, 4.2.1, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 4.6.0, 4.7.1, 4.7.2, 4.8.0, 4.8.1)
ERROR: No matching distribution found for web3==4.8.2

and

~/market-maker-keeper $ ./test.sh
./test.sh: 2: ./test.sh: source: not found
Traceback (most recent call last):
  File "/home/pi/.local/bin/py.test", line 6, in <module>
    from pytest import main
  File "/home/pi/.local/lib/python3.7/site-packages/pytest.py", line 13, in <module>
    from _pytest.fixtures import fixture, yield_fixture
  File "/home/pi/.local/lib/python3.7/site-packages/_pytest/fixtures.py", line 839, in <module>
    class FixtureFunctionMarker(object):
  File "/home/pi/.local/lib/python3.7/site-packages/_pytest/fixtures.py", line 841, in FixtureFunctionMarker
    params = attr.ib(convert=attr.converters.optional(tuple))
TypeError: attrib() got an unexpected keyword argument 'convert'

now that i think of it... this second part may because the first problem but i am still puting it here just incase

**Comment by grandizzy** [comment]
make sure you use virtualenv / python3 https://github.com/makerdao/market-maker-keeper#3-getting-started-installation

let's keep such discussions in RC #keeper channel
