### ISSUE TITLE
ReadMe seems to be missing details about the incentives paid to keepers?

### ISSUE THREAD

**Issue by tomachinz** [makerdao/market-maker-keeper#143]
The word incentive is mentioned twice:
`The DAI Stablecoin System incentivizes external agents, called keepers, to automate certain operations around the Ethereum blockchain.`
and
`A big part of the DAI Stablecoin System (DSS) is the incentivization of external agents, called Keepers (which can be human but are typically automated bots).`
but appears missing reference to any incentivisation. Point 9 `Running Market Maker Keepers` explains the command line arguments, but nothing about how the payouts are calculated. I guess that is coming from another part of the program (Maker DAO say), but for noobs like me would be good to have a link to say... the page on the component where this does reside. (I'll see about adding it and adding a pull request once I find it?!)

**Comment by Jay991** [comment]
I think this is [CDP Keeper](https://github.com/makerdao/cdp-keeper). Once you find a risky CDP you get rewarded. Looks like it's not stable yet

**Comment by tomachinz** [comment]
OK so I can now see that MIN_MARGIN is a percentage (let's say 20%), I think perhaps liquidation ratio is always permanently locked at 150%... Comprehension could maybe come to my brain assuming I have MIN_MARGIN plus TOP_UP_MARGIN, ETH_FROM is my own keepers money-pile (arguably the entire point of running one) from where top ups come, but since I am unsure about what MAX_SAI is or means, nor AVG_SAI (maybe the current Sai value in USD?), it all gets a bit much for Mr Noob right here :) Perhaps they are valued in Dai not USD?

**Comment by MikeHathaway** [comment]
It sounds like there is some confusion about the role of market-maker-keepers. This repository is primarily concerned with market-making software. Collateralization ratios and liquidation auctions are handled by auction-keepers: https://github.com/makerdao/auction-keeper.

I've update the README to clarify this distinction: https://github.com/makerdao/market-maker-keeper/pull/217.

For answers to more detailed questions, feel free to stop by the Maker community chat at chat.makerdao.com.

**Comment by tomachinz** [comment]
Thanks Mike!
