### ISSUE TITLE
kucoin-python==2.0.5

### ISSUE THREAD

**Issue by saumyabratadutt** [makerdao/market-maker-keeper#149]
ERROR: Could not find a version that satisfies the requirement kucoin-python==2.0.5 (from versions: 0.1.1)
ERROR: No matching distribution found for kucoin-python==2.0.5

I keep getting the above mentioned error in keeper and uniswap price feed installation.
Is there any way to fix it?

Thank you

**Comment by MikeHathaway** [comment]
The issue should be resolved with this PR: https://github.com/makerdao/market-maker-keeper/pull/150
