### ISSUE TITLE
Extract the asynchronous EthGasStation API to a separate project

### ISSUE THREAD

**Issue by reverendus** [makerdao/market-maker-keeper#7]
May be useful to other keepers in the future as well.

**Comment by reverendus** [comment]
Ultimately a pip package...?

**Comment by Swixx** [comment]
@reverendus Can this close because of [this](https://github.com/makerdao/ethgasstation-client)?

**Comment by reverendus** [comment]
yeah @Swixx

**Comment by Swixx** [comment]
@reverendus I don't have the ability to do so, maybe you can so we can keep the issues up-to-date?

**Comment by reverendus** [comment]
I think you should contact someone in the `makerdao` org. @Swixx

**Comment by grandizzy** [comment]
Closing as not applicable anymore
